/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ulbra.projetoEscola;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Leonardo
 */
public class FrResultados extends javax.swing.JFrame {

    /**
     * Creates new form Resultados
     */
    public FrResultados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        edtNumero = new javax.swing.JTextField();
        btnAdicionar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtListaGeral = new javax.swing.JTextArea();
        btnRemover = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        btnPar = new javax.swing.JButton();
        btnImpar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnMedia = new javax.swing.JButton();
        btnMaior = new javax.swing.JButton();
        btnMenor = new javax.swing.JButton();
        btnOrdenar = new javax.swing.JButton();
        btnDesordenar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gerenciador Escola");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 32, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Informe um Número: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 111, -1, -1));

        edtNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtNumeroKeyPressed(evt);
            }
        });
        jPanel1.add(edtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 145, 396, 38));

        btnAdicionar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        btnAdicionar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnAdicionarKeyPressed(evt);
            }
        });
        jPanel1.add(btnAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 140, 156, 45));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Lista de Números: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 231, -1, -1));

        txtListaGeral.setColumns(20);
        txtListaGeral.setRows(5);
        jScrollPane1.setViewportView(txtListaGeral);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 271, 384, 290));

        btnRemover.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });
        jPanel1.add(btnRemover, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 270, 120, 41));

        btnAtualizar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 330, 120, 40));

        btnListar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });
        jPanel1.add(btnListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 518, 120, 42));

        btnPar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPar.setText("Pares");
        btnPar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParActionPerformed(evt);
            }
        });
        jPanel1.add(btnPar, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 267, 120, 44));

        btnImpar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnImpar.setText("Impares");
        btnImpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImparActionPerformed(evt);
            }
        });
        jPanel1.add(btnImpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 329, 120, 43));

        btnBuscar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 457, 120, 43));

        btnMedia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnMedia.setText("Média");
        btnMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMediaActionPerformed(evt);
            }
        });
        jPanel1.add(btnMedia, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 390, 120, 44));

        btnMaior.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnMaior.setText("Maior");
        btnMaior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaiorActionPerformed(evt);
            }
        });
        jPanel1.add(btnMaior, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 390, 120, 41));

        btnMenor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnMenor.setText("Menor");
        btnMenor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenorActionPerformed(evt);
            }
        });
        jPanel1.add(btnMenor, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 457, 120, 43));

        btnOrdenar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnOrdenar.setText("Desordenar");
        btnOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarActionPerformed(evt);
            }
        });
        jPanel1.add(btnOrdenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 580, 140, 41));

        btnDesordenar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDesordenar.setText("Ordenar");
        btnDesordenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesordenarActionPerformed(evt);
            }
        });
        jPanel1.add(btnDesordenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 520, 120, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        Gerenciador obj = new Gerenciador();
    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        obj.adicionar(Integer.parseInt(edtNumero.getText()));
        obj.adicionar2(Integer.parseInt(edtNumero.getText()));
        edtNumero.setText("");
        edtNumero.requestFocus();
        btnListar.doClick();
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnAdicionarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAdicionarKeyPressed
    
    }//GEN-LAST:event_btnAdicionarKeyPressed

    private void edtNumeroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtNumeroKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnAdicionar.doClick();
        }
    }//GEN-LAST:event_edtNumeroKeyPressed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        btnListar.doClick();
        int cod, novoNum;
        cod = Integer.parseInt(JOptionPane.showInputDialog("Qual índice? "))-1;
        novoNum = Integer.parseInt(JOptionPane.showInputDialog("Qual o novo número? "));
        obj.atulizar(cod, novoNum);
        txtListaGeral.setText(obj.listar());
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        txtListaGeral.setText(obj.listar());
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnParActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParActionPerformed
        txtListaGeral.setText(obj.listarPar());
    }//GEN-LAST:event_btnParActionPerformed

    private void btnImparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImparActionPerformed
        txtListaGeral.setText(obj.listarImpar());
    }//GEN-LAST:event_btnImparActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        txtListaGeral.setText(obj.listar());
        int cod;
        cod = Integer.parseInt(JOptionPane.showInputDialog("Qual indice você quer remover?"));
        if(JOptionPane.showConfirmDialog(null, "Tem certeza que deseja remover esse número ","CONFIRME",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
           obj.remover(cod-1);
           txtListaGeral.setText(obj.listar());
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMediaActionPerformed
        txtListaGeral.setText(obj.listar());
        JOptionPane.showMessageDialog(null, "A média dos números adicionados é: "+obj.calcularMedia());
    }//GEN-LAST:event_btnMediaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        int cod;
        cod=Integer.parseInt(JOptionPane.showInputDialog("Qual número você quer procurar na lista?"));
        JOptionPane.showMessageDialog(null, obj.buscar(cod));
    }//GEN-LAST:event_btnBuscarActionPerformed
    private void btnOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarActionPerformed
        obj.retornarOrdem();
        txtListaGeral.setText(obj.listar());
    }//GEN-LAST:event_btnOrdenarActionPerformed

    private void btnMaiorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaiorActionPerformed
        JOptionPane.showMessageDialog(null,"O maior número da lista é: "+obj.descobrirMaior());
    }//GEN-LAST:event_btnMaiorActionPerformed

    private void btnMenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenorActionPerformed
       JOptionPane.showMessageDialog(null,"O menor número da lista é: "+obj.descobrirMenor()); 
    }//GEN-LAST:event_btnMenorActionPerformed

    private void btnDesordenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesordenarActionPerformed
        obj.ordenarOriginal();
        txtListaGeral.setText(obj.listarDesordem());
    }//GEN-LAST:event_btnDesordenarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrResultados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnDesordenar;
    private javax.swing.JButton btnImpar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnMaior;
    private javax.swing.JButton btnMedia;
    private javax.swing.JButton btnMenor;
    private javax.swing.JButton btnOrdenar;
    private javax.swing.JButton btnPar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JTextField edtNumero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtListaGeral;
    // End of variables declaration//GEN-END:variables
}
